export const GET_CHALLENGES = 'GET_CHALLENGES';
export const DELETE_CHALLENGE = 'DEETE_CHALLENGE';
export const ADD_CHALLENGE = 'ADD_CHALLENG'; 
export const CHALLENGES_LOADING = 'CHALLENGES_LOADING'; 